In [1]:
from util import *
import matplotlib.pyplot as plt
import seaborn as ses

In [2]:
mall_id = "m_7168"
index = 0
train = load_train()
train = train[train.mall_id == mall_id]
predict = pd.read_csv("../result/offline_predict/{}_{}.csv".format(mall_id,index))
_train_index,_valid_index=get_last_one_week_index(train)
_valid = train.iloc[_valid_index]
_train = train.iloc[_train_index]
error = _valid.loc[_valid.index[predict.predict != predict.real]]
correct = _valid.loc[_valid.index[predict.predict == predict.real]]

In [90]:
df, (train_index, train_use_wifi, train_matrix), (test_index, test_use_wifi, test_matrix) = get_wifi_cache(mall_id)

In [45]:
error[error.user_id=="u_53682"]

,user_id,shop_id,time_stamp,longitude,latitude,wifi_infos,category_id,shop_longitude,shop_latitude,price,mall_id,i_loc
312,u_53682,s_293082,2017-08-27 13:30,116.863008,40.326947,b_41615054|-67|false;b_33310185|-70|false;b_35...,c_30,116.863439,40.327104,48,m_7168,15
313,u_53682,s_293082,2017-08-27 13:40,116.863183,40.327201,b_4640640|-90|false;b_29650327|-80|false;b_628...,c_30,116.863439,40.327104,48,m_7168,16
315,u_53682,s_736490,2017-08-27 13:50,116.863037,40.327038,b_85554|-61|false;b_62802|-49|false;b_40418853...,c_36,116.863532,40.327242,45,m_7168,18
316,u_53682,s_295706,2017-08-27 13:00,116.863184,40.327202,b_8518720|-74|false;b_36036564|-72|false;b_571...,c_13,116.863428,40.327109,50,m_7168,19

In [46]:
correct[correct.user_id=="u_53682"]

,user_id,shop_id,time_stamp,longitude,latitude,wifi_infos,category_id,shop_longitude,shop_latitude,price,mall_id,i_loc
314,u_53682,s_293082,2017-08-27 13:00,116.862942,40.327455,b_57104369|-67|false;b_62803|-80|false;b_37055...,c_30,116.863439,40.327104,48,m_7168,17

In [65]:
error[error.shop_id=="s_293082"].shape

(139, 12)

In [104]:
train_matrix[train[train.shop_id=="s_293082"].i_loc]

array([[ -65.,  -70., -115., ..., -115., -115., -115.],
       [ -70., -115., -115., ..., -115., -115., -115.],
       [ -67., -115., -115., ..., -115., -115., -115.],
       ...,
       [ -64.,  -74., -115., ..., -115., -115., -115.],
       [-115.,  -72.,  -72., ..., -115., -115., -115.],
       [ -81.,  -79.,  -80., ..., -115., -115., -115.]])

In [96]:
train_matrix[error[error.shop_id=="s_293082"].i_loc]

array([[ -65.,  -70., -115., ..., -115., -115., -115.],
       [ -70., -115., -115., ..., -115., -115., -115.],
       [-115.,  -66., -115., ..., -115., -115., -115.],
       ...,
       [-115., -115., -115., ..., -115., -115., -115.],
       [ -68., -115., -115., ..., -115., -115., -115.],
       [ -69.,  -72.,  -72., ..., -115., -115., -115.]])

In [97]:
train_matrix[correct[correct.shop_id=="s_293082"].i_loc]

array([[ -67., -115., -115., ..., -115., -115., -115.],
       [ -70.,  -80.,  -77., ..., -115., -115., -115.],
       [-115., -115.,  -64., ..., -115., -115., -115.],
       ...,
       [-115.,  -77.,  -80., ..., -115., -115., -115.],
       [-115., -115., -115., ..., -115., -115., -115.],
       [-115., -115., -115., ..., -115., -115., -115.]])

        predict      real
0      s_293805  s_293082
1      s_295706  s_293082
2      s_293082  s_293082
95     s_293805  s_293082
99    s_2303129  s_293082
144    s_293082  s_293082
169   s_2310712  s_293082
182    s_293785  s_293082
254    s_295706  s_293082
382   s_2783591  s_293082
430    s_293704  s_293082
431     s_77146  s_293082
432    s_293785  s_293082
433    s_293785  s_293082
594    s_295706  s_293082
602    s_293031  s_293082
678    s_295706  s_293082
744   s_2783591  s_293082
833    s_295706  s_293082
856   s_2783591  s_293082
922    s_295706  s_293082
963   s_2783591  s_293082
964    s_456529  s_293082
966    s_293082  s_293082
967    s_293805  s_293082
983    s_293805  s_293082
999   s_2783591  s_293082
1032   s_293082  s_293082
1072  s_2783591  s_293082
1096   s_293785  s_293082
...         ...       ...
5650   s_293082  s_293082
5682   s_293785  s_293082
5683   s_293082  s_293082
5690   s_293082  s_293082
5710   s_293082  s_293082
5730   s_295706  s_293082
5741  s_2303129  s_293082
5766   s_295706  s_293082
5767   s_293082  s_293082
5776   s_295706  s_293082
5804   s_295706  s_293082
5864   s_295706  s_293082
5961  s_2783591  s_293082
5981   s_295706  s_293082
5996   s_295706  s_293082
6062   s_293082  s_293082
6088   s_293082  s_293082
6132   s_293082  s_293082
6146   s_293082  s_293082
6161   s_293082  s_293082
6193   s_293082  s_293082
6209  s_2783591  s_293082
6263   s_294228  s_293082
6321  s_2783591  s_293082
6365   s_293785  s_293082
6408   s_293785  s_293082
6425   s_293082  s_293082
6426   s_293805  s_293082
6427   s_301215  s_293082
6444   s_295706  s_293082

[198 rows x 2 columns]